# This file was generated by GoReleaser. DO NOT EDIT.
cask "c9s" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "f52d31efc46b148091bd8d1857b2a8cf80225b3296666b636335f79283ce5280"
      url "https://github.com/torosent/c9s/releases/download/v#{version}/c9s_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "c9s"
  desc "Terminal UI for Apple Containers (k9s for container)"
  homepage "https://github.com/torosent/c9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "c9s"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/c9s"]
    end
  end

  # No zap stanza required

end
